### ISSUE TITLE
User Settings Page

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#100]
**User Story**

AS A USER I want check and edit my account settings.

**Acceptance Criteria**
- The user could change email address, first name and last name by using "User settings" form.
- The button "Change password" should show change password form.

**Additional context**
https://projects.invisionapp.com/d/main#/console/19172407/401732880/preview

**Comment by gosiafelis** [comment]
Could you please:
- Change button label 'Edit' -> 'Edit settings'
- Remove '.margin-bottom-medium' fo the settigns <form> element
- For the class 'read-only' change padding-bottom: 30px
- In the edit mode please decrease 10px padding below labels
