### ISSUE TITLE
Register to Keen via Google

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#101]
**User Story**

AS A **USER** I want to be able to register to Keen platform by using Google account so that I do not need to provide my login and password.

**Acceptance Criteria**
- The Google login button is available in the form.
- The authentication error should be show after unsuccessful login attempt.

**Comment by gosiafelis** [comment]
Use the one you feel is better:

"There has been a problem with accessing your data from Google(/Github). You can register by using your email." 

"We were not able to access your data from Google(/Github). You can register by using your email."
