### ISSUE TITLE
Signup form inputs icons

### ISSUE THREAD

**Issue by gosiafelis** [keen/keen#103]
**USER STORY**
**As a new user** that registers to Keen, **I want to** be able to use my password generator **so that** I do not need to type and memorize it.

I noticed during user testing the following:
If a user uses some kind of password generator, the button to generate a password is placed on the right side of the password input. 
Our current 'Show/hide password' button is there and hovers the pass generator button.

We should move all buttons/icons form the input level to the label level -> Check the screenshot
Applies to:
- Show/hide password
- CVV info icon

![Screenshot 2020-02-05 at 11.31.09.png](https://images.zenhubusercontent.com/5dee08cd89fe1caf0ca2dc83/b80b2072-4e4a-4dfe-bb9f-4eef584ac5a4)

**Comment by maciejrybaniec** [comment]
Adjust input width
