### ISSUE TITLE
Small changes to the documentation view

### ISSUE THREAD

**Issue by gosiafelis** [keen/keen#106]
USER STORY
**As a** Kenn customer, **I want to** see that all the pages look consistent **so I** feel that I am buying a complete product.

We need to apply some changes to the documentation page so it has similar styling to the new marketing page.

Changes:
- navigation background-color
- font color adjustment
- search color adjustment
- replacing the logo with the new version
- replacing links in the navigation

Design:
https://projects.invisionapp.com/d/main#/console/19342722/403966303/preview

Keen logo:
https://drive.google.com/drive/folders/1lmxSQNY1SAK8zWgubvSIIke6yRC03JRY

**Comment by maciejrybaniec** [comment]
Remove footer from docs (optional)

**Comment by gosiafelis** [comment]
Please change the link for 'getting started' to docs/streams
