### ISSUE TITLE
Prepare sample data

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#111]
Prepare the sample events in Keen.io project `5c87b64ec9e77c0001cf5b6e`.

**Acceptance Criteria**
1. There should be events ready to present in `monthly interval` - (6 months timeframe).
2. There should be events ready to present in `yearly interval` - (6 years timeframe).
3. There should be events ready to present in `minutely interval` - (1 day timeframe).
4. There should be events ready to present in `weekly interval` - (5 weeks timeframe).
5. There should be events ready to present in `hourly interval` - (1 day timeframe).

**Comment by apryka** [comment]
```
projectId: '5011dc0e5f546f1fcd000000',
savedQueryName: [
'pageviews_6months_monhtly',
'pageviews_6years_yearly',
'pageviews_1day_minutely',
'pageviews_5weeks_weekly',
'pageviews_1day_hourly',
]
```
