### ISSUE TITLE
Fav icon

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#112]
**User Story**

AS A USER I want to see a fav icon on browser card SO I could identify Keen.io based on logo.

**Acceptance Criteria**
- The FavIcon is displayed in Keen.io User Management app.

**Additional context**
For fav icon ask @gosiafelis

**Comment by gosiafelis** [comment]
You can find favicons in this folder:
https://drive.google.com/drive/folders/1GjTHGq0wWLrZBm-Clm1TbeKDBIvYT2If
