### ISSUE TITLE
Explorer V6 Extraction Error

### ISSUE THREAD

**Issue by jacob-vasquez** [keen/keen#114]
**Describe the bug**
Running extraction analysis extracts all properties and not just target property 

**To Reproduce**
1. Go to Explorer V6
2. Select Event Collection
3. Select Extraction Analysis Type 
4. Select property to extract
5. Select run query
6. See error

**Expected behavior**
Expect to see an extraction of the target property

**Actual behavior**
All of the data from the event is pulled

**Screenshots**
If applicable, add screenshots to help explain your problem.![image.png](https://images.zenhubusercontent.com/5e2728df52024fc8834b7489/cbb27fd0-dcd9-41cc-9f75-2968a3651bee)

**Environment**
Staging

**Comment by maciejrybaniec** [comment]
1) Check if this bug exist on production environment.

Moved to "Ready to estimate"

**Comment by maciejrybaniec** [comment]
Ask Wiktor about support from Back-End side.

**Comment by dariuszlacheta** [comment]
Extraction of the target properties is not supported from API side
