### ISSUE TITLE
Donut Chart

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#116]
**User Story**

AS A USER I want to visualize data by using Donut Chart

**Acceptance Criteria**
- Support for basic information inside chart - "Total" with sum of values.
- Support theming based on already defined interface
- Integrated with Legend, Tooltip, Title, SubTitle components
- Integrated with `@keen.io/dataviz`.
- The border size could be adjusted by user.
- Stories with use cases and example data implemented in Storybook

**Comment by gosiafelis** [comment]
1. 'Total' element inside the donut is not centered vertically. 
Please center the whole element (number with text 'total') vertically.

**Comment by gosiafelis** [comment]
2. Can we add an option to change the donut weight?

**Comment by apryka** [comment]
@maciejrybaniec by donut weight we mean a slider that changes the radius of the inner circle. Maybe this is a good point to create another ticket to merge donut/pie into one component?
