### ISSUE TITLE
Bar Chart - stacked

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#117]
**User Story**

AS A USER I want to visualize data by using Stacked Bar Chart

**Acceptance Criteria**
- Support theming based on already defined interface
- Integrated with Legend, Tooltip, Title, SubTitle components
- Support values on bars.
- Hover on percent stack should show tooltip with all values for data-series.
- Integrated with `@keen.io/dataviz`.
- Stories with use cases and example data implemented in Storybook
- Tooltip in "stacked" mode should display list and bold text for active bar data series. - specify with @gosiafelis.

**Comment by gosiafelis** [comment]
Is this point implemented:
- Support values on bars.
?

**Comment by maciejrybaniec** [comment]
Add support for values on bars.
