### ISSUE TITLE
Support for Enter/Return keys in forms

### ISSUE THREAD

**Issue by gosiafelis** [keen/keen#124]
**User Story**

AS A USER I want to navigate through the forms with keyboard SO I could fill the forms quicker. 

**Acceptance Criteria**
- Forms could be submitted by pressing `Enter` / `Return` key.
- The improvement is applied to: _Login_, _Reset Password_, _Set New Password_, _Name organization_, _Accept invitation_

**Comment by maciejrybaniec** [comment]
This part should be extracted to separate component that accepts `isSubmitting` and `submitForm` props.
```
      <form
        onKeyDown={keyEvent => {
          if ((keyEvent.charCode || keyEvent.keyCode) === 13) {
            keyEvent.preventDefault();
            if (!isSubmitting) submitForm();
          }
        }}
      >
```

**Comment by gosiafelis** [comment]
This scope works fine on staging.

What should be addressed in new tickets:
- Support 'Enter' on registration pages
- Support 'Tab' navigation for buttons
