### ISSUE TITLE
Platform E-mail template

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#126]
**General**
As a quick win we want to unify e-mail templates in our platform and develop simple message template.

**User Story**

AS A USER I want to have common e-mail template SO the user experience across e-mail messages will be unified.

**Acceptance Criteria**
- The Keen Logo, header and footer is part of e-mail template.
- The e-mail container could contain any text / message.
- The e-mail is validated with W3C Markup validator

**Additional context**
- For additional details about design ask @gosiafelis 
https://projects.invisionapp.com/d/main#/console/19172407/401575792/preview

**Comment by gosiafelis** [comment]
Fonts for the email: Lato, Helvetica, Arial
