### ISSUE TITLE
Adjust pages footer to the new styling

### ISSUE THREAD

**Issue by gosiafelis** [keen/keen#131]
**User Story**

AS A **KEEN MEMBER** I want to have footer implemented according to new design SO I the marketing page and platform will be more consistent. 

**Acceptance Criteria**
- The new styling is applied to elements.
- All links in footer are updated.
- The new Keen Logo is used.

**Additional Context**
- Guides page should be updated (https://keen.io/guides/ ).
- Documentation page should be updated.
- Ask @gosiafelis for additional details.

**Comment by gosiafelis** [comment]
In the documentation, the footer is covered on the left side by the menu bar. 
Can we move the content slightly to the right?

![Screenshot 2020-03-13 at 09.27.18.png](https://images.zenhubusercontent.com/5dee08cd89fe1caf0ca2dc83/1fef61f6-68a7-4b70-88e3-0cd6f9be3ee1)

**Comment by gosiafelis** [comment]
2. 'Resources' link is wrong. Please change to 'https://keen.io/resources/'

**Comment by apryka** [comment]
@gosiafelis fixed and deployed to stg

**Comment by gosiafelis** [comment]
@apryka works fine now. Thanks

**Comment by gosiafelis** [comment]
@reanndvorscek the new footers are on production :) could you please check?

**Comment by reanndvorscek** [comment]
@gosiafelis Looks great. Thank you!
