### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#133]
**User Story**

AS A **PRODUCT OWNER** I want to have dedicated and user friendly 404 page SO the traffic from this page will be handled.

**Acceptance Criteria**
- The 404 page is implemented in user management application.
- The page is implemented according to design.
- The hovers and user experience should be consistent with Marketing 404 page.

**Additional Context**
@gosiafelis - provide design for 404 page.

**Comment by gosiafelis** [comment]
Here is the design prepared by the US side:
https://invis.io/BUVJDE5SF7M#/400592554_404_Error_

**Comment by gosiafelis** [comment]
On staging it works fine
