### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#134]
**Description**
Handle rate limiting response code **429** for requests in User Management app.

**Acceptance Criteria**
- The proper message is displayed for the user.

**Additional Context**
- Clarify message with @gosiafelis 
- GET /users/signup/validate-email
- POST /users/signup/
- POST /users/login

**Comment by gosiafelis** [comment]
- GET /users/signup/validate-email
Sorry, too many signup attempts. Please try again later or contact us at support@keen.io.

- POST /users/signup/
Too many signups from your side (IP? - should w say that?). It feels strange. Please try again later or contact us at support@keen.io.

- POST /users/login
Sorry, too many login attempts. Please try again later or contact us at support@keen.io.
