### ISSUE TITLE
Auto-collector Dashboard

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#138]
**Describe the bug**
One of charts on auto-collector dashboard do not display any data.

**To Reproduce**
1. Go to https://keen.github.io/auto-collector-dashboard/
2. Check "Views By Top 3 Sources" chart

**Expected behavior**
The data should be presented on chart

**Actual behavior**
There is no data displayed.

**Environment**
Production / Staging

**Comment by apryka** [comment]
![Screenshot 2020-03-13 at 07.17.07.png](https://images.zenhubusercontent.com/5c7e3784e4920f4ae3852d1d/9c989a8f-4299-4161-91da-3fce667f3c3b)

checked a moment ago and the data is displayed on 'Views By Top 3 Sources

**Comment by apryka** [comment]
`projectId: '5011efa95f546f2ce2000000',
saved_query_name: 'autocollector-dashboard-demo---count-pageviews-top-referrers-previous-7-days-interval-daily'`

both are active on prod



![Screenshot 2020-03-13 at 07.24.43.png](https://images.zenhubusercontent.com/5c7e3784e4920f4ae3852d1d/72b11684-f379-4a39-8818-7e914a008b73)

**Comment by maciejrybaniec** [comment]
@apryka  could You please notify Jorge that the issue is resolved ?
