### ISSUE TITLE
First page after login & users with access to projects only

### ISSUE THREAD

**Issue by gosiafelis** [keen/keen#142]
**As a** Keen user, **I want** to go to my projects automatically after login **so I can** start analyzing my data right away.

We have some navigation issues after the new sign up release. 
When user logins to the platform(the standard login link), he should be redirected to the projects view.

Cases:

**1. User is an admin of the organization**
NOTE: The user has access to the organizations section - the link is visible.
When he logs into the platform, he should be redirected to the project's context:
- the first project on the list(historically - check org root page) - current mechanism
or (better option)
- the last project that he visited in the last session

**2. User is an admin of the project**
NOTE: The user does not have access to the organizations section - the link is hidden.
When he logs into the platform - same as 1st case.

**Comment by maciejrybaniec** [comment]
Should be handle by Back-End
