### ISSUE TITLE
Comprehensive documentation for Heatmap

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#151]
**User Story**

AS A USER I want to have a comprehensive documentation SO I could easily understand data visualization domain and use tools provided by Keen.

**Comment by gosiafelis** [comment]
The document with the short description and some examples of how we can present the chart:
https://docs.google.com/document/d/1M5grooYNeBDVoOBkeN3ZPtjSy0Ofv9ClfqVfQrUBPfw/edit#heading=h.49n3fjmfrbip

**Comment by gosiafelis** [comment]
When we have business/presentation examples ready - I will prepare more explanation about specific use cases. We can have more detailed information there. How to use colors, scales, categorization etc.
