### ISSUE TITLE
Plan Limitations

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#152]
**User Story**

AS A USER I want to have a clearly defined plans' limitations messages SO I can better understand the Keen platform.

**Additional context**
- We need to define the copies and messages to inform the user about plans' limitations. 
- This should be applied to Explorer, Dashboard Creator, Access Keys components.

List from the stories:
a. Disable S3 component for free plan and for the Team plan is the customer doesn't pay for Add-On. Add proper messaging on how to get it.
b. Cached queries limit message
c. Events limit message (small overuse is possible)
d. Queries limit message (small overuse is possible)
e. Explorer not available on Free plan - disable and message
f. Creator not available on Free plan - disable and message
g. Free plan - 3 months data extraction limit
h. Access Keys limits messages

**Comment by gosiafelis** [comment]
**1. S3 limitation**
S3 - Free plan
https://invis.io/FPWCGOEWMKJ#/409415439_free-S3
S3 - Team plan
https://invis.io/FPWCGOEWMKJ#/409541327_team-S3

**3. Queries limit message
4. Events limit message**
https://docs.google.com/document/d/1lzxDfL2JnEF1JOpzxiT5_dt15pM-Ukuiq-HIRgSH1-U/edit

**5. Explorer not available on Free**
https://invis.io/FPWCGOEWMKJ#/409401549_free-Explorer

**6. Dashboard not available on Free**
https://invis.io/FPWCGOEWMKJ#/409401550_free-Dashboard

**Comment by gosiafelis** [comment]
**c. Events limit message
d. Queries limit message**
https://docs.google.com/document/d/1lzxDfL2JnEF1JOpzxiT5_dt15pM-Ukuiq-HIRgSH1-U/edit

**e. Explorer not available on Free**
https://invis.io/FPWCGOEWMKJ#/409401549_free-Explorer

**f. Dashboard not available on Free**
https://invis.io/FPWCGOEWMKJ#/409401550_free-Dashboard

**Comment by gosiafelis** [comment]
**e. Explorer not available on Free**
https://invis.io/FPWCGOEWMKJ#/409401549_free-Explorer

**f. Dashboard not available on Free**
https://invis.io/FPWCGOEWMKJ#/409401550_free-Dashboard

**Comment by gosiafelis** [comment]
**story no 7**
**b. Cached Queries & Cached datasets limits**

Free plan - CQ & CD not available:
https://invis.io/FPWCGOEWMKJ#/409415438_free-CachedDatasets
https://invis.io/FPWCGOEWMKJ#/409641680_free-CachedDatasets-Activity-Page

Other plans - limits message:
Shown for cached queries - should be added analogically for cached datasets
https://invis.io/FPWCGOEWMKJ#/409641679_limit-Cached-Queries-Compute
https://invis.io/FPWCGOEWMKJ#/409563601_limit-Cached-Queries
https://invis.io/FPWCGOEWMKJ#/409641678_limit-Cached-Queries-Activity

**Comment by gosiafelis** [comment]
**story no 8**

**e. Explorer not available on Free**
https://invis.io/FPWCGOEWMKJ#/409401549_free-Explorer

**f. Dashboard not available on Free**
https://invis.io/FPWCGOEWMKJ#/409401550_free-Dashboard

**Comment by gosiafelis** [comment]
**story no 11, 12** 

**Access Keys limitations**

Free plan - Access Keys not available
https://invis.io/FPWCGOEWMKJ#/409733208_free-AccessKeys

Other plans - message about the limit
https://invis.io/FPWCGOEWMKJ#/409733207_limit-AccessKeys
