### ISSUE TITLE
Heatmap plot

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#153]
**User Story**

AS A USER I want visualize my using heatmap SO that I could present my data with color-coded systems.

**Acceptance Criteria**
- The `scaleX` and `scaleY` settings are available for chart plot
- Support for theming
- Two modes for color ranges: `discrete` and `continuous`. 
- The implementation should use the current design system.

**Additional context**
- Ask @gosiafelis for additional interactions like "hover", "clicks"
- https://projects.invisionapp.com/d/main#/console/19037699/396877855/preview

**Comment by gosiafelis** [comment]
We need to improve the shadows for boxes.

1. The shadow itself needs adjustments - is it possible to work on this in codepen or something? I could play with the filter.

2. The shadow is cut on edges. Check funnel chart how it should look like:
https://keen.github.io/keen/?path=/docs/visualizations-funnel-chart-widget--widget
![Screenshot 2020-03-19 at 11.50.17.png](https://images.zenhubusercontent.com/5dee08cd89fe1caf0ca2dc83/3a890101-028a-4004-8ca2-278ed0333e7f)
![Screenshot 2020-03-19 at 11.50.11.png](https://images.zenhubusercontent.com/5dee08cd89fe1caf0ca2dc83/0d132ffa-a2ca-4f0c-9f48-84669dcb7666)

**Comment by gosiafelis** [comment]
Creating a separate ticket for general shadows improvements
