### ISSUE TITLE
Table chart design

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#154]
We need a design to a table chart plot and widget.

**Requirements** 
- General design for table elements (row, cells, headers).
- Interactions with "table" plot are defined (hovers, clicks).

Specification:
https://docs.google.com/document/d/1mzJltRS-VksM4czeqO_ZPV5cmzrrwZhNzODyPuKyybY/edit#

Design:
https://invis.io/D2WKW4LGN3Z

**Comment by gosiafelis** [comment]
Check 'Alert' tables cases
