### ISSUE TITLE
Billing details

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#156]
**Describe the bug**
Credit card details do not seem to be correctly displayed when just patchy details are filled in

**To Reproduce**
1. Go to Keen Platform
2. Edit billing details for organization by filling only partial details
3. Check billing settings

**Expected behavior**
The details are displayed correctly without unnecessary commas.

**Actual behavior**
There are unnecessary commas.

**Screenshots**
https://slack-files.com/T024Y6VHU-FUSV0N0AD-46c6252b09

**Environment**
Staging

**Comment by piotrek-buchman** [comment]
And what about missing expiration date? https://keen.slack.com/archives/CU4EDL8MS/p1583761402020200

**Comment by gosiafelis** [comment]
The title 'Billing address' should be always added if there are some details filled.

I removed 'street address' in Chargify and the title disappeared. 
![Screenshot 2020-03-25 at 13.46.46.png](https://images.zenhubusercontent.com/5dee08cd89fe1caf0ca2dc83/94f0e754-7d80-4925-a579-d57f6ec304a2)

**Comment by gosiafelis** [comment]
Can we detect that the country is not selected and do not display '--' ?
It happened when I removed the country in Chargify (they have '--' in their select)
![Screenshot 2020-03-25 at 13.49.53.png](https://images.zenhubusercontent.com/5dee08cd89fe1caf0ca2dc83/4531510f-7acd-4512-a1bc-b18a6c0a342d)
