### ISSUE TITLE
System E-mails

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#157]
**General**
Check system e-mail's consistency and search for design differences.

**Output**
- A common ticket with listed things that need to be adjusted.

**Comment by gosiafelis** [comment]
1. Content text is too large. The main text should be 16px. Small text should be 14px.
2. Want to learn more section should have font-size: 14px for all elements. 
3. Icons at the bottom (books, slack) should have margin-right: 10px

**Comment by gosiafelis** [comment]
**Password reset email:**
1. Remove margin/padding below 'Forgot your Keen password?
2. Make two sentences "If you did not make this request ....." small - 14px
![Screenshot 2020-03-12 at 11.07.08.png](https://images.zenhubusercontent.com/5dee08cd89fe1caf0ca2dc83/892c4e6f-026f-4beb-8296-6641b08d8ff9)

**Comment by gosiafelis** [comment]
**Invite to the project:**
1. Remove margin/padding below "You have been invited to the Keen project new project." (first line)
2. Change button copy to 'Register now'

**Comment by gosiafelis** [comment]
**Invite to organization:** unregistered user
1. Change email subject to "Invite to Keen organization"
2. Remove margin/padding below the first line.
3. Change button copy to 'Register now'

**Comment by gosiafelis** [comment]
Invite to the organization/project - registered user
Only general fixes

**Comment by gosiafelis** [comment]
1. Add an empty line after 'Hi there'
2. Start the first sentence with the uppercase letter.

![Screenshot 2020-03-20 at 17.08.59.png](https://images.zenhubusercontent.com/5dee08cd89fe1caf0ca2dc83/738204fa-390b-44c0-9748-19c2e2254c91)

**Comment by maciejrybaniec** [comment]
@apryka ask back-end for status

**Comment by apryka** [comment]
it was deployed on stg 3 days ago so it's ready for testing

**Comment by gosiafelis** [comment]
I checked 
- reset password, 
- your password has been changed
- invite to org
 
Thay are ok
