### ISSUE TITLE
Replace current logo with new Keen logo

### ISSUE THREAD

**Issue by reanndvorscek** [keen/keen#159]
**User Story**

AS A USER I want to know the full correct name of the company, 

**Acceptance Criteria**
- Criteria A: User must now that Keen is now A Chargify Company 
- Criteria B

**Additional context**
Need to swap out the current logo for the "Keen - A Chargify Logo"!

[Keen-Chargify-light-M (1).png](https://images.zenhubusercontent.com/5e67a4fd015a7a80381cd377/5e921949-2b45-450f-a2d0-9b7610cc4670)

**Comment by gosiafelis** [comment]
SVG files here:
https://drive.google.com/drive/folders/1vvSg5KZP8rsQHxzgh2QT3yeu-sFvu6Ot

**Comment by maciejrybaniec** [comment]
User management app - ✅ (login, register etc.)
The pull request for Keen platform is in code review process.

**Comment by gosiafelis** [comment]
@reanndvorscek Logos has been changed. They are already on the production. You can test if there is a correct logo everywhere.

Please let us know here, so we know if the ticket can be closed :)

**Comment by reanndvorscek** [comment]
@gosiafelis this looks good as well! This ticket can be closed
