### ISSUE TITLE
Pricing calculator design

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#160]
**User Story**

AS A USER I want to have a pricing calculator SO I could choose a proper plan for my business needs.

**Output**
- Design for calculator
- Re-usable range component

Story from the document:
10. As a Keen’s marketing page visitor I want to be able to estimate the cost of the service using Pricing Calculator. It should allow visitors to select the number of events and number of queries using sliders and gets recommendation for the cheapest pricing plan supporting the numbers and its price including overages.

**Comment by gosiafelis** [comment]
From Reann:

Here are the pricing page details from our call last week:
- [](https://docs.google.com/spreadsheets/d/1j0jHYQdFynYFY2DtoSG4J9FtsFD9OzKXu0puiTJf3PY/edit#gid=0
)
- Sketch file attached 

We like these website pricing page calculators:
- [](https://agencyanalytics.com/pricing)
- [](https://segment.com/plans/)

**Comment by gosiafelis** [comment]
**Calculator design:**
https://invis.io/BJWNQCL9E6H#/411850985_Calculator-Green

- calculator
- calculator on the page
- mobile version

Info about the logic:

**Pricing Breakpoints:**

Breakpoints will be dependent on the sum of the total price, which will include base plan price, any event or query overages, and/or any additional services selected.  

- Price threshold for Business Plan: $800 
(ie, the calculator will show recommendation of "Team Plan" until the sum of the total price hits $800. Then recommended plan will switch to Business)

- Price threshold for Custom Plan: $2000

- S3 Streaming
If toggle is 'on', add additional $100 to the Team Plan
Included in Business Plan. Even if toggle is 'on', do not add additional $100 to Business Plan. 

- If custom SSL toggle is 'on', automatically recommend Business Plan. 

- If Role-Based Access toggle is 'on', automatically recommend the Business Plan. 

- If Annual Billing toggle is 'on', recommendation should display the total price with 10% discount.

**Comment by gosiafelis** [comment]
Plan includes: (Team)
25 Access Keys
5 Cached Queries
5 Cached Datasets

Plan includes: (Business)
50 Access Keys
50 Cached Queries
50 Cached Datasets

Plan includes: (Custom)
Tell us what you need

**Comment by gosiafelis** [comment]
Reference for the listing additional elements:
https://segment.com/plans/

**Comment by gosiafelis** [comment]
Update: For the recommendations, we use only paid plans.

**Comment by gosiafelis** [comment]
Content for tooltips:

**S3**
Stream your full-resolution, enriched data to Amazon S3 and harness the power of your data anywhere. This is useful for backups, routing events to third parties, SQL-based analysis.

**Role-based access:**
Guarantee each of your users can only explore the data they need, with completely customizable permission tiers. API Keys can be used to grant access to particular data points or the results of particular queries.

**Custom SSL**
Leverage the encrypted communication to Keen on your custom, branded domain.

@maciejrybaniec check if it makes sense.
