### ISSUE TITLE
empty billing details

### ISSUE THREAD

**Issue by apryka** [keen/keen#163]
neither CC details nor billing portal link is available then this section is empty.
this happens immediately after the sign-up before we synchronize the billing portal link.

![image.png](https://images.zenhubusercontent.com/5c7e3784e4920f4ae3852d1d/68a10246-f0cf-4b50-8509-131cbc94702f)

**Comment by gosiafelis** [comment]
Maybe we could add a message 'We are setting up your billing account' ?

**Comment by gosiafelis** [comment]
I signed up with the new account on staging.

Right after registration, I checked the 'Billing details' page. There was a message like for the non-owner
""The organization owner can update payment method in Chargify's Billing Portal.
Do you need help? Contact us at contact@keen.io" + details displayed.

My thought was "wtf, I am an owner - I've just created this organization"
