### ISSUE TITLE
Slider Component

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#173]
**Info**
Create re-usable slider component.

**Acceptance Criteria**
- The "rail" element should have possibility to be adjusted to specific usage for eg. Heatmap.
- Possibility to limit the range by changing "Knob" position - with maximum and minimum values.
- The story should be created.
- Unit tests are written.

**Additional context**
https://projects.invisionapp.com/d/main#/console/19037699/396877854/preview
https://www.framer.com/api/tutorial/

**Comment by gosiafelis** [comment]
@dariuszlacheta Slider with the ruler
https://invis.io/Q4VA2R33TYB#/409932812_Slider

**Comment by gosiafelis** [comment]
1. When the size of the controls is increased, they are not centered.
2. There is an issue with rendering values
![Screenshot 2020-03-24 at 11.41.06.png](https://images.zenhubusercontent.com/5dee08cd89fe1caf0ca2dc83/409de7f2-1162-470a-877a-0672702777ae)
![Screenshot 2020-03-24 at 11.43.41.png](https://images.zenhubusercontent.com/5dee08cd89fe1caf0ca2dc83/1ebf58f5-dae2-44b8-a79c-633a8d796949)

**Comment by gosiafelis** [comment]
1. When changing the slider bar size, the 'inactive' range is broken.
![Screenshot 2020-03-25 at 16.01.57.png](https://images.zenhubusercontent.com/5dee08cd89fe1caf0ca2dc83/6fa85ef8-c9a6-4f06-a5ef-9939d17bda4e)

2. There is still an issue with the text over text
![Screenshot 2020-03-25 at 15.58.38.png](https://images.zenhubusercontent.com/5dee08cd89fe1caf0ca2dc83/1dd61029-793e-4dc3-9514-0d857934d57b)

3. Changing the number of steps apply to the ruler in the wrong way
![Screenshot 2020-03-25 at 16.00.01.png](https://images.zenhubusercontent.com/5dee08cd89fe1caf0ca2dc83/f8f9ef0e-0480-4181-8866-1324c4a5454c)

4. Tooltip text is too large

5. Tooltip animation is broken - it should not 'jump'
