### ISSUE TITLE
Area Chart

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#182]
**User Story**

AS A USER I want visualize my data by using area chart so I could present it in proper form.

**Acceptance Criteria**
- Extend `Line Chart` with additional `areaMode` - `boolean`.
- For color series - create a `Gradient` component that will be applied to `Area` space.
- Unit tests are written.
- Stories are created 

**Additional context**
- https://projects.invisionapp.com/d/main#/console/19037699/396877844/preview

**Comment by gosiafelis** [comment]
Gradient for non-stacked areas: 
- we do not need to modify color from the palette
- form max value: 80% opacity to 0(min value): 20% opacity.
- it should be possible to turn on/off 'gradient'
- when the gradient is turn off: fill with the solid color
