### ISSUE TITLE
Bubble Chart Research

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#183]
**Details**

Research use cases for using `Bubble` chart in context of Keen clients. 

**Acceptance Criteria**
- Determine if we need to create a new type of analysis to handle use cases.

**Comment by gosiafelis** [comment]
"The bubble chart is designed to visually convey three or four dimensions of data, which is more than just marketing buzz. This means **your data needs to have at least three fields on your record that you’ll want to convey graphically all at once**. 

This could be a date field (x-axis), a cost figure (y-axis), and the ROI of the project (bubble size)."

**Comment by gosiafelis** [comment]
Conclusion:
Example
https://www.displayr.com/what-is-a-bubble-chart/

Sum property - cost
Group by - country
Timerange: 1 year

Sum property - safty
Group by - country
Timerange: 1 year

**Comment by maciejrybaniec** [comment]
To sum up - we need three queries to create a all required dimensions.
