### ISSUE TITLE
Add Hubspot tracking code

### ISSUE THREAD

**Issue by michalpierog** [keen/keen#189]
## Tracking code installation

Copy and paste this tracking code into every page of your site, just before the `</body>` tag:
```html
<!-- Start of HubSpot Embed Code -->
<script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/469751.js"></script>
<!-- End of HubSpot Embed Code -->
```

[Detailed description](https://knowledge.hubspot.com/reports/install-the-hubspot-tracking-code)

The same tracking code should be used for Staging and Production. It must not be included for any other environment (dev, test etc.)

Tracking code must not be added for paths which contains '/root/'.

**Comment by salahhazaea** [comment]
<script type="text/javascript" id="hs-script-loader" async defer src="//js-na1.hs-scripts.com/22686003.js"></script>
