### ISSUE TITLE
Placeholder Limit

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#198]
**Description**
Create re-usable placeholder component that could be used across Keen platform to inform user about plan limitation.

**Acceptance Criteria**
- Re-usable block of code is implemented

**Design**
- https://projects.invisionapp.com/d/main?origin=v7#/console/19550364/409415438/preview?scrollOffset=1093

**Comment by gosiafelis** [comment]
Lock image:
https://drive.google.com/drive/folders/14AvbYII61VH-6C8mEr9hHwUirhnitFBH

**Comment by gosiafelis** [comment]
Places that will be 'locked':

- Explorer panel
- Dashboards panel

- Cached queries component (Compute & Activity page)
- Cached datasets component (Compute & Activity page)
-  Access keys (Access page)
