### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#2]
Create a re-usable Text component that could be used in charts library.

**Functional requirements**
1. Adjusting font-size, color, font-family, alignment, font-weight, font-style.
2. Width should be adjusted based on parent container.

**Acceptance Criteria**
1. The unit test are written.
2. The story is created for component.

**Comment by gosiafelis** [comment]
Design:
https://projects.invisionapp.com/d/main#/console/19066623/397949666/preview
