### ISSUE TITLE
Table Chart Plot

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#204]
**User Story**

AS A USER I want visualize my data as a table so I could present my data with that type of visualization.

**Technical Requirements**
- The table elements are part of @keen.io/ui-core package.
- Unit tests are written.

**Acceptance Criteria**
- The data could be sorted by clicking on table header (ascending and descending).
- Clicking on cell should copy the value to clipboard.
- Possibility to resize a column width.
- The table header should be fixed by default with option to "static" mode.
- Vertical scroll for columns.

**Comment by dariuszlacheta** [comment]
https://projects.invisionapp.com/d/main#/console/19649378/410879252/preview
