### ISSUE TITLE
Bubble Chart Legend

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#206]
**User Story**

AS A USER I want to have a human-readable legend for Bubble Chart SO I could better understand correlation between data series.

**Acceptance Criteria**
- Unit tests are written
- Integration at Widget level.
- The component is part of `@keen.io/charts` package components.

**Additional context**
- @gosiafelis provide design.
- https://www.d3-graph-gallery.com/graph/bubble_legend.html

**Comment by gosiafelis** [comment]
Bubbles legend:
![Screenshot 2020-03-25 at 14.34.05.png](https://images.zenhubusercontent.com/5dee08cd89fe1caf0ca2dc83/ed6ba959-b5ef-4f24-9c08-f5d96b2725e7)

Color: gray-500
Bubbles opacity:
big - 30%
medium - 50%
small - 90%

Title: Lato bold 12
Ruler: Lato regular 12
