### ISSUE TITLE
Gauge Chart Plot

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#220]
**User Story**

AS A USER I want visualize my data as a Gauge meter so I could present my data with that type of visualization.

**Acceptance Criteria**
- Stories are created.
- Unit tests are written.
- Support theming based on current interface.

**Comment by gosiafelis** [comment]
1. 'Border' is too wide. It should have 5px by default. The inner 'progress curve' should have 30px.

2. Font-size of the progression number could adjust to the size of the whole chart. Right now, when the chart is small, the number is too big and looks bad. 
![Screenshot 2020-04-03 at 11.56.13.png](https://images.zenhubusercontent.com/5dee08cd89fe1caf0ca2dc83/c4703037-be97-40c3-8fc7-5e715a2000a0)

3. We could add a caption to the number - as in the donut chart.

**Comment by gosiafelis** [comment]
4. As default color for the inner curve set the gradient from gray100 to blue400
