### ISSUE TITLE
Bubble Chart Widget

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#222]
**User Story**

AS A USER I want have a Bubble Chart Widget so I could integrate it on my website.

**Comment by gosiafelis** [comment]
1. There should be min and max size of the bubble set so the chart is readable.
Min radius = 5px
Max radius = 40px

2. In the tooltip, we could highlight somehow the property that is connected to the bubble size.

**Comment by maciejrybaniec** [comment]
3. We need to add support for title - on Axes.

**Comment by gosiafelis** [comment]
2. Separating the property that is connected to the bubble size:
![bubble-tooltip.png](https://images.zenhubusercontent.com/5dee08cd89fe1caf0ca2dc83/e872269b-38be-4d73-8e52-74ed03dd3cf9)
