### ISSUE TITLE
HubSpot Integration

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#225]
**User Story**

AS A Sales Manager I want to receive information about company during Sign Up process so I could check details about client in HubSpot platform.

**Description**
We need to extend a first step of sign up process with additional field - company name.

**Acceptance Criteria**
- The company name filed is required in first step until the user mark checkbox "I do not have company".
- Filling the form with company name after successful signup should redirect user to Keen platform.
- The Back-End should receive additional field **company_name** in sign up request.
- Filling the form no providing company field - should redirect user to re-name organization page.
- Unit tests are written.

**Additional context**
@gosiafelis provide designs.

**Comment by gosiafelis** [comment]
https://invis.io/FPWCGOEWMKJ#/411587501_1024-Mock-Signup-1stStep_-1-_Copy

**Comment by maciejrybaniec** [comment]
@gosiafelis - checkbox with active state

**Comment by gosiafelis** [comment]
When the checkbox is active - the Company name field should be deactivated:
1. Label opacity 50%
2. Line color - gray-500
https://projects.invisionapp.com/d/main#/console/19550364/411587501/preview

**Comment by gosiafelis** [comment]
'Company name' label should be clickable - click on the label focus on the field. Check other fields in the form

**Comment by maciejrybaniec** [comment]
Fixed.

**Comment by gosiafelis** [comment]
From the visual point of view, everything is fine
