### ISSUE TITLE
Table Chart Widget

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#255]
**User Story**

AS A USER I want to have Table Chart Widget so I could integrate it directly on my website.

**Acceptance Criteria**
- The "Extraction" analysis is handled by @keen.io/parser
- The @keen.io/dataviz supports "table" widget
- Stories are created

**Comment by gosiafelis** [comment]
Is there an option to change the text color?

**Comment by gosiafelis** [comment]
It would be nice to check the table in the storybook in the card context. To see if it works well with different backgrounds.
