### ISSUE TITLE
Interval Slider - improvements

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#269]
**User Story**

AS A USER I want to select value on slider by clicking on rail or scale tick so I do not need to drag a slider control.

**Acceptance Criteria**
- The value is selected based on click event performed on <Rail /> component.
- The value is adjusted based on click on scale tick.

**Comment by gosiafelis** [comment]
1. Change the slider gradient color to: green100 - green500
2. For mobile version decrease ruler font size to 12px
3. Add formatting for the tooltip number - separate thousands(millions etc) with comma.
4. For the desktop version add more padding for the left side of the white container. (It should be ~50px total)
