### ISSUE TITLE
Card

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#3]
Create a re-usable Card component that could be used in charts library.

**Functional requirements**
1. Adjusting background-color, border css properties (none, light and normal).
2. Adjusting border-radius property based on pixels (according to pre-defined preset)
3. Turn on/off box-shadow (turned on by default).

**Acceptance Criteria**
1. The unit test are written.
2. The story is created for component.
3. Implemented according to designs.

**Comment by gosiafelis** [comment]
Design:
https://projects.invisionapp.com/d/main#/console/19066623/397548810/preview

**Comment by gosiafelis** [comment]
I don't know if there is an updated version of card on storybook - there is the wrong box-shadow color.

Please use for cards. box-shadow: 0px 2px 4px 0px rgba(29,39,41,0.15);
