### ISSUE TITLE
Persisted query parameters

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#35]
**Describe the bug**
The query parameters after saving are persisted for next created query.

**To Reproduce**
1. Navigate to Explorer v6
2. Create a new query and save it
3. Click "+" to create another query
4. Set query parameters
5. Save query

**Expected behavior**
A query should be saved.

**Actual behavior**
The error showed up - regarding to incorrect query params

**Environment**
Production and Staging

**Comment by gosiafelis** [comment]
I save one query and click '+' (new query).
The query form is cleared (values are back to default).
