### ISSUE TITLE
Explorer switch

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#38]
**Describe the bug**

The Explorer Classic instance is re-created each tab switch.

**To Reproduce**
1. Go to keen.io
2. Navigate to Explorer tab
3. Select Explorer Classic
4. Switch to Explorer v6
5. Switch back to Explorer Classic

**Expected behavior**
A explorer instances should be mounted only once and re-used.

**Actual behavior**
A new instance of Explorer Classic is created every tab switch.

**Environment**
Production and Staging

**Comment by stof** [comment]
Well, another solution is to keep creating the explorer classic on tab switch, but making sure it is actually unmounted when switching away.
