### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#4]
Create a re-usable Legend component that could be used in charts library. 

**Functional requirements**
1. Set border on top or left based on layout type.
2. Adjust the alignment.
3. Turn on/off legend card.
4. **Adjusting color, font-family, font-size, font-style, font-weight.**
5. Layout - vertical / horizontal.
6. Slider for legend content based on defined columns / rows.
7. Text elipsis.
8. Handlers for mouse events.

**Acceptance Criteria**
1. The unit test are written.
2. The story is created for component.
3. Implemented according to designs (without title).

**Comment by maciejrybaniec** [comment]
Design: https://projects.invisionapp.com/d/main#/console/19066623/398149109/preview

**Comment by gosiafelis** [comment]
Design:
https://projects.invisionapp.com/d/main#/console/19066623/398149109/preview

**Comment by gosiafelis** [comment]
@maciejrybaniec added hover state and inactive state at the bottom of the page in invision.

**Comment by maciejrybaniec** [comment]
Re-estimated to 2 story points

**Comment by maciejrybaniec** [comment]
@gosiafelis add additonal acceptance criteria for styling

**Comment by gosiafelis** [comment]
- default font should be Lato
- accent border should be blue-500

**Comment by gosiafelis** [comment]
Please check two cases:

1. Vertical legend with arrows - the margin between items doesn't work
https://keen.github.io/keen/?path=/story/components-legend--column-slider

2. Horizontal legend 1 row - there should be no bottom margin
https://keen.github.io/keen/?path=/story/components-legend--row
