### ISSUE TITLE
Add internal Keen metrics

### ISSUE THREAD

**Issue by gosiafelis** [keen/keen#46]
It would be useful to start tracking how many people use:

- Explorer Classic
vs
- Explorer v6

and

- Dashboard Classic
vs
- Creator

It will help us define:
- whether people switch to new versions 
- how many users are affected by changes in new versions

Later on, we would investigate what we should improve in new versions to make people switch from the old ones.

**Comment by maciejrybaniec** [comment]
Need to define - how to determine that explorer is used.

**Comment by gosiafelis** [comment]
My idea what to measure:

Explorers:
- clicks on tabs (explorer v6 vs explorer classic)
- clicks on 'run query' in each version
- clicks on 'save query' in each version

Dashboards:
- clicks on tabs (Creator vs Dashboard classic)
- clicks on 'new dashboard/create dashboard now' in each version
- clicks 'edit dashboard' in each version
