### ISSUE TITLE
Optional order field in group_by section, cannot be reset

### ISSUE THREAD

**Issue by dariuszlacheta** [keen/keen#48]
**Describe the bug**
When value is picked for order field in group_by section it cannot be reset to no value, causing an error.

**To Reproduce**
1. Go to 'explorer'
2. Prepare a query with group_by target property and order e.g. ASC
3. Run query
4. See error: `The value you specified for direction is invalid. It must be either 'ASC' or 'DESC'. You specified: '{'direction': u'', 'property_name': 'result'}'.`

**Expected behavior**
Order field is optional and user should be able to reset a value.

**Actual behavior**
Value cannot be reset for order field.

**Screenshots**
![Screenshot 2019-12-19 at 11.30.30.png](https://images.zenhubusercontent.com/5c58486f93a5605cab276d6b/bd777a65-b79d-4d71-ba15-d22b569dfe45)

**Environment**
Production

**Comment by gosiafelis** [comment]
Seems to be working, but there is another bug with ordering:
Ascending order behave strange:
1. When I display all data, it doesn't seem to work when I change order direction.
2. When I limit data to for example 10 samples it displays different samples (highest/lowest) but the order in the plot is still wrong.
[https://drive.google.com/open?id=1DomnE2-4An_6S37wWzGJOlQwHnNfHean](url)
