### ISSUE TITLE
Cartesian Grid

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#5]
Create a re-usable Cartesian Grid component that could be used in charts library. 

**Functional requirements**
1. Adjust the line color.
2. Turn on/of vertical and horizontal lines.

**Acceptance Criteria**
1. The unit test are written.
2. The story is created for component.
3. Implemented according to designs (without title).

**Comment by gosiafelis** [comment]
Keen default grid lines should have: 1px solid #E1E2E4
