### ISSUE TITLE
Dashboard Creator doesn't render any charts for onboarding

### ISSUE THREAD

**Issue by apryka** [keen/keen#51]
Steps to re-create:
1. go to keen.io and create an account
2. answer onboarding questions
3. example saved queries should be visible in explorer
4. go to Creator
5. list of dashboards is correct, but dashboards are empty, no charts are rendered
6. Dashboard Classic works fine

expected behavior:
Creator should display charts within a dashboard

**Comment by gosiafelis** [comment]
Still doesn't work properly. Creator has two dashboards listed, but they are empty.
![Screenshot 2019-12-27 at 14.16.41.png](https://images.zenhubusercontent.com/5dee08cd89fe1caf0ca2dc83/a951999d-f5d5-4b7c-8528-059f9400e495)

**Comment by gosiafelis** [comment]
Works just fine now
