### ISSUE TITLE
Integrate Legend with Bar Chart

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#54]
Integrate a Legend component with Bar Chart. 

**Functional requirements**
1. The hover on specific legend series should fade out other data series. 
2. Legend position in widget should be aligned based on configuration.

**Acceptance Criteria**
1. The unit test are written.
2. The story is update for widget component.

**Comment by gosiafelis** [comment]
Comment to multiple results case:
https://keen.github.io/keen/?path=/story/dataviz-bar-charts--multiple-results

When user 'turns off' one series, other series in one group should be brought closer.

**Comment by gosiafelis** [comment]
There is no fade out legend hover.
