### ISSUE TITLE
Pie Chart Plot

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#57]
Create a plot for Pie Chart component. 

**Functional requirements**
1. The component interface is aligned with already defined types.
2. The component should support theming.
3. Hover / Clicks - interactions to be defined with @gosiafelis 
4. Should support padding adjustment between series.

**Acceptance Criteria**
1. The unit test are written.
2. The story is created for component.

**Comment by gosiafelis** [comment]
1. Labels by default should have: font-family: Lato Regular
2. When labels are set to outside, they should adjust to the outside color - black for light background, white for dark background.
3. On the slice hover, the label could increase size font-size: 16px (in general 2 points bigger)
