### ISSUE TITLE
Charts text formatting

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#62]
**Describe the bug**
The text formatting sometimes cut off the funnel and pie chart title.

**To Reproduce**
1. Go to keen.io
2. Navigate to Dashboard Creator
3. Create a Funnel and Pie chart.
4. Check title format.

**Expected behavior**
The text is clearly visible.

**Actual behavior**
A text is not fully visible.

**Screenshots**
![Zrzut ekranu 2019-12-30 o 09.39.09.png](https://images.zenhubusercontent.com/5de75a167d01dba94df7723d/e0df135e-0329-4e56-889d-393995a1f387)

**Environment**
Production and Staging

**Comment by gosiafelis** [comment]
It still doesn't look good.
![Screenshot 2020-01-29 at 16.52.26.png](https://images.zenhubusercontent.com/5dee08cd89fe1caf0ca2dc83/df738fee-67d2-4ece-a564-4d4d22677c90)

**Comment by gosiafelis** [comment]
@maciejrybaniec please check this ticket - it seems there are 3 different tickets in one
