### ISSUE TITLE
Fetching multiple queries at same time

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#65]
**Describe the bug**
Keen-Analysis mixed options when performing fetch of multiple queries.

**To Reproduce**
1. Use Keen-Analysis to get result of multiple queries at same time
2. Set sortBy + groupBy + interval properties for one query and groupBy property for second query.
3. Perform queries

**Expected behavior**
The queries results are fetched correctly.

**Actual behavior**
The queries options are mixed up and keen-analysis crashed 

**Environment**
Production

**Additional context**
https://github.com/keen/keen-analysis.js/issues/61

**Comment by maciejrybaniec** [comment]
How to reproduce

```
  const firstQuery =  client.query({"analysis_type":"count","event_collection":"signups","timeframe":"this_1_days","timezone":3600,"interval":"monthly","filters":[]});

  const secondQuery =  client.query({"analysis_type":"count","event_collection":"signups","timeframe":"this_14_days","timezone":3600,"interval":"weekly","filters":[],"group_by":["keen.id"],"order_by":{"property_name":"result","direction":"ASC"},"limit":5});

  client
    .run([firstQuery, secondQuery])
    .then(res => {
      console.log('res', res);
    })
    .catch(err => {
      console.log('error', err);
    })
```

**Comment by maciejrybaniec** [comment]
I tested in our Storybook - everything works ok. 
We could publish a new version.

**Comment by apryka** [comment]
new version of keen-analysis has been released https://github.com/keen/keen-analysis.js/releases/tag/v3.5.0
