### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#7]
Create a re-usable Tooltip component that could be used in charts library. 

**Functional requirements**
1. Function to customize formatting 
2. Adjust tooltip arrow position.
3. Adjust background-color, color, font-family, opacity, box-shadow.
4. Two modes light / dark.

**Acceptance Criteria**
1. The unit test are written.
2. The story is created for component.
3. Implemented according to designs (without title).

**Comment by gosiafelis** [comment]
https://projects.invisionapp.com/d/main#/console/19066623/399399990/preview
