### ISSUE TITLE
Sort pre-formatted data in Table

### ISSUE THREAD

**Issue by jeubank12** [keen/keen#735]
**Describe the bug**
TableChart sorts data after it has been formatted. In the event of time/date formatting this causes problems. Is there a workaround to set a custom sort function or specify that data should be sorted before formatting?

**To Reproduce**
1. Create a TableChart or TableChartWidget, backed by a query which extracts timestamps
2. Set the following property 
```
formatValue={value => moment(value).format(`MMM D [(]h:mm A[)]`)}
```
3. Sort the data in the table by clicking a header
4. Observe example sorting order descending: Jan 2, Jan 16, Jan 1

**Expected behavior**
The data should be sorted descending: Jan 16, Jan 2, Jan 1

**Actual behavior**
Data is actually sorted descending: Jan 2, Jan 16, Jan 1
This is because it is being sorted as a string

**Screenshots**
![image](https://user-images.githubusercontent.com/11911979/105891380-d1ef7e00-5fcd-11eb-93cf-5cbec0897194.png)

**Environment**
Production

**Additional context**
We don't want to change the format string to `MMM DD [(]h:mm A[)]` (which would produce Jan 02) if we don't have to

**Comment by maciejrybaniec** [comment]
Hi @jeubank12 

Thank You for providing such detailed description about how to reproduce the issue. 
We discussed it today within a team a decided to change chart behaviour to always apply sort settings on raw unformatted data.

Here is a pull request addressing this issue:
https://github.com/keen/keen/pull/736

After code review I will publish a new version.

**Comment by jeubank12** [comment]
@maciejrybaniec excellent, thank you! I realized this morning that this would have manifested further as Feb XX sorts as a string between Dec and Jan

**Comment by maciejrybaniec** [comment]
Hi @jeubank12,

Today morning we published new packages versions:
- @keen.io/dataviz@2.4.10
- @keen.io/widgets@2.2.29
- @keen.io/charts@2.5.28
