### ISSUE TITLE
Route change handler

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#75]
Add route change handler to `DashboardBuilder` so we could notify Appcues tracking about url changes.

**Functional requirements**
1. Generic route change handler is added to `DashboardBuilder`.

```
const dashboard = new DashboardBuilder({
  onRouteChange: () => {
     window.Appcues.page()
  }
});
```

**Acceptance Criteria**
1. The unit test are written.
2. Appcues tracking is available in page global scope.

**Docs**
https://docs.appcues.com/article/389-single-page-applications-spas

**Comment by JAC-Keen** [comment]
I'm going to re-open.
I'm testing, and coordinating with Appcues support engineer to ensure all settings and configurations of the workflows are in fact set up to the best practice specs.

Here's screen shots and attached are links videos to what I tried to run today and still seeing an issue in having the tool tip workflow not have a break without having to refresh.

Appcues.debug()
Appcues.show('-Ly6MOs5WswW-Zs5CqGy') 
Appcues.clearShow('-Ly6MOs5WswW-Zs5CqGy') 

https://drive.google.com/open?id=12nA3HIPRAfgpJImbFmcEzH38AuTK4Rsv

^I login, use the URL on my personal project:
https://keen.io/projects/5bce2b59c9e77c00018f5028/#/

Clear my Browser Settings and history twice.
But yes I still have to force refresh to continue the walk through.

![Screen Shot 2020-02-26 at 9.38.33 AM.png](https://images.zenhubusercontent.com/5d9e42a9c1eccb0001c6e3df/b4b072e7-4fc0-41d9-9e34-4d24476117ed)
