### ISSUE TITLE
Pie/Donut chart render glitch

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#79]
**Describe the bug**
Resizing browser viewport 

**To Reproduce**
1. Go to keen.io
2. Open dashboard with pie / donut chart.
3. Resize browser viewport (down and up). 

**Expected behavior**
All charts plots are visible.

**Actual behavior**
A donut / pie chart plot is missing.

**Environment**
Production and Staging

**Additional context**
https://keen.slack.com/archives/C02NSBDDV/p1579038913025700

**Comment by gosiafelis** [comment]
Seems to work now
