### ISSUE TITLE
Register Page

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#82]
**User Story**

AS A **USER** I want to be able to sign up for a Keen plan via public page.

**Description**

Create a new registration page that will allow user to sign up for a Keen.

**Acceptance Criteria**

1. **General**

- A register form is consisted of two steps independent steps. 
- The list of subscription plans are visible at each registration step.
- After successful registration process the form for re-naming organization is visible.
- The register form could be open with pre-selected subscription plan.
- The form validation should be performed dynamically at each step.
- The bar shows the registration process progress.

2. **User Details** 
- The name, e-mail and password fields need to be provided or user could authenticate via Google / GitHub.
- The "billing details" form step should be enabled after clicking "Continue to Billing Info" button or successful authorizing via Google / GitHub.

3. **Billing Info**
- The card number, CVV code, expiry date, first and last name needs to be provided to validate card.
- The CVV field should contain "info" icon that shows tooltip with description.
- The country (ISO_3166-1) field selected as United States - shows additional billing address form with required fields for Avalara Taxes integration: state (ISO_3166-2), zip code, address. 
- The field for additional billing emails should be visible and allow to provide multiple e-mail addresses.

**Comment by maciejrybaniec** [comment]
name to be confirmed based on HubSpot integration requirements.

**Comment by maciejrybaniec** [comment]
user story for non existing plan

**Comment by maciejrybaniec** [comment]
default plan on chargify side

**Comment by gosiafelis** [comment]
Added tooltip here:
https://projects.invisionapp.com/d/main#/console/19172407/400803312/preview
