### ISSUE TITLE
Login to Keen

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#83]
**User Story**

AS A **USER** I want to be able to login to Keen platform via public page.

**Acceptance Criteria**
- A login form is consisted of two fields login and password that are required.
- The form validation should be performed dynamically and after submission.
- The authentication error should be show after unsuccessful login attempt.
- The link to "forgot password" is available in the form and after click the user is redirected to password reset process form.
- The link to "demo request" page should be available at login page.

**Comment by gosiafelis** [comment]
1. Add text 'Show/Hide' next to the eye icon - like on the registration page.
2. When a user clicks 'Log in' and there is a loading phase, change the button text to 'Loading'.
3. Change validation messages from 'required'(empty fields) to 'Please enter your email in the format: username@example.com' ,  'Please enter your password.'
4. Change invalid email validation to: 'Invalid email format. Valid example: username@example.com'

**Comment by dariuszlacheta** [comment]
Requested changes addressed in: https://github.com/keen/front-end-user-management/pull/39

@gosiafelis

**Comment by gosiafelis** [comment]
@dariuszlacheta one more thing - can we add submitting by clicking 'Enter'? Now user have to click the button.

**Comment by dariuszlacheta** [comment]
@gosiafelis This can be done, please create separate issue to add submitting form by 'Enter' to all forms.

**Comment by gosiafelis** [comment]
(y)
