### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#86]
**User Story**

AS A **USER** I want to be able to reset my password so that I could setup new password and access keen platform.

**Acceptance Criteria**
- The e-mail field is visible and required.
- The form validation should be performed dynamically and after submission.
- The message is visible after successful form submission. 
- The "Back to login" link is available and click should redirect to login page.
- The "Request demo" link is available below the form.

**Comment by gosiafelis** [comment]
Please fix:
1. Email field validation:
field is empty: Please enter your email
invalid email: Please enter your email in the format: username@example.com

**Comment by maciejrybaniec** [comment]
@gosiafelis ready on staging env
