### ISSUE TITLE
Join the Organization

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#87]
**User Story**

AS A **USER** I want to be able to login to join specific organization so that I could start using Keen.

**Acceptance Criteria**
- The "join" process could be finished by providing username and password fields and clicking "Create account" button.
- The form validation should be performed dynamically and after submission.
- The "join" process could be finished by authenticating via GitHub / Google account.
- The name of organization name and e-mail from invitation is visible.
- The invitation link is valid for 24 hours and dedicated message is visible for expired invitation.(**WON'T DO - flow changed**)

**Comment by maciejrybaniec** [comment]
multiple invitation e-mails edge case

**Comment by gosiafelis** [comment]
If we do not have possibility to use 'Send a new invitation link' option, please display a message:

Red box:
"Your invitation link has expired. Get in touch with your manager or platform admin to request a new one."

and leave the blue 'Go to homepage' link.

(Applies to this page:
https://projects.invisionapp.com/d/main#/console/19172407/401423657/preview )
