### ISSUE TITLE
Set New Password

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#94]
**User Story**

AS A **USER** I want to setup a new password after opening reset link.

**Acceptance Criteria**
- The password and password2 fields is required.
- The validators check that two password fields value are equal.
- The create new password button is visible.
- After successful password setup user should be redirected to login with proper information.

**Comment by maciejrybaniec** [comment]
@gosiafelis add a messages

**Comment by gosiafelis** [comment]
When the user fills 'reset password form' there should be the message displayed and the button should change to the 'Loading' state. 

After 4s (time should be enough to read the message - may be more/less) he is redirected to the login page.

https://projects.invisionapp.com/d/main#/console/19172407/403730690/preview

**Comment by gosiafelis** [comment]
Also please check - I've added validation hints to the reset password form:
https://projects.invisionapp.com/d/main#/console/19172407/401577948/preview

**Comment by gosiafelis** [comment]
Message for the expired rest link:
https://projects.invisionapp.com/d/main#/console/19172407/403734356/preview
