### ISSUE TITLE
Organization Select Page

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/keen#97]
**User Story**

AS A **USER** I want to be able to change organization context in Keen platform.

**Acceptance Criteria**
- The proper info is displayed if user do not have any organization.
- The click on "organization card" should redirect user to platform with selected organization context.

**Design**
https://projects.invisionapp.com/d/main#/console/19172407/401775026/preview
https://projects.invisionapp.com/d/main#/console/19172407/401755354/preview

**Comment by gosiafelis** [comment]
1. Please change the background image to shapes-org.png, so it is wider
https://drive.google.com/open?id=1qQDFedncumNu7rJV5-8x0F3bQra6YtTD

2. Add hover color effect to the organization boxes:
hover background color: #F2F2F2
additionally, the right arrow can move a few pixels to the right on hover 
(.org-list-item a: background icon can be set by default on 98% horizontally and on hover move to 100%)

3. Decrease vertical padding inside the boxes:
.org-list-item{ padding: 10px 30px}
